### ISSUE TITLE
ModuleNotFoundError: No module named '__m2crypto'

### ISSUE THREAD

**Issue by francesco1119** [dsoprea/M2CryptoWindows#2]
On Python 3.8 after installation I'm experiencing this: 

```
Traceback (most recent call last):
  File "RSA.py", line 8, in <module>
    from M2Crypto import RSA
  File "C:\Program Files\Python38\lib\site-packages\M2Crypto\__init__.py", line 22, in <module>
    import __m2crypto
ModuleNotFoundError: No module named '__m2crypto'
```

Any idea if I'm doing something wrong?

**Comment by vmisiko** [comment]
I have the same problem, i installed m2Crptowin64 in python3.7 in windows 10, but i ama getting the same errors.
I have read that m2crpto of version 0.28.1 supports python 3, probably in other os, but for windows m2Cryptowin64 is of version 0.21.0 and probably does not support python 3.

**Comment by francesco1119** [comment]
My suggestion @vmisiko is to use Windows Subsystem for Linux (WSL) on Windows 10.
The WSL2 is even faster and you can install it [this way](https://scotch.io/bar-talk/trying-the-new-wsl-2-its-fast-windows-subsystem-for-linux). 

I stop trying to install it on Windows

**Comment by vmisiko** [comment]
The problem is that, i don't what to use a vm in windows, i already have a dual boot of windows and ubuntu. i have a django project in windows, for which requires a small bit of of m2crypto lib. I had seen m2crypto python 3.5 of some people in discussion, but i do not understand the installation procedure very well.
